name: neuronify
version: 1.0
summary: Neuronify
description: |
    Education neural network app
confinement: strict

apps:
    neuronify:
        command: desktop-launch custom-qt-helper neuronify
        plugs:
          - unity7
          - x11
          - opengl
          - pulseaudio

parts:
  move:
    plugin: dump
    source: snapdump
  conf:
    plugin: dump
    source: .snapcontents
  packages:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - xserver-xorg-video-intel
      - qt5-default
  helpers:
    plugin: nil
    after:
      - move # NOTE move and conf must be here due install error for desktop-qt5 otherwise
      - conf
      - packages
      - desktop-qt5
