language: cpp
branches:
  except:
  - appveyor
matrix:
  include:
  - os: osx
    before_install:
      - brew update
      - brew install p7zip
      - bash .travis/qt5-mac.sh $(pwd) extra-charts 3d base declarative graphicaleffects imageformats macextras multimedia quickcontrols quickcontrols2 sensors svg tools translations xmlpatterns
      - export PATH=$(pwd)/5.7/clang_64/bin:$PATH
    before_deploy:
      - git clone https://github.com/iltommi/macdeployqtfix.git
      - python macdeployqtfix/macdeployqtfix.py neuronify.app/Contents/MacOS/neuronify /usr/local
      - macdeployqt neuronify.app -qmldir=. -dmg
    deploy:
      skip_cleanup: true
      provider: releases
      file: neuronify.dmg
      on:
        tags: true
      api_key:
        secure: WJ9YTjPf8GWZ4PmdVoPubtL0CBU+cAIIMFjTpeOKwOLX1vH3zFkdwAz1nbY28CWWhm+YQwWVWwByZOI9hePsf5t6wtkWfJB4wzgrKEcIyKHMHmjaMYc+fp6V//3f7Z4Kc6vYn7wNNy1i9zgA8VVr2A4u8Rf1i7Euio4SLpey17w=
  - os: linux
    dist: trusty
    sudo: required
    services: docker
    before_deploy:
    - docker run -v $(pwd):/app snapcore/snapcraft bash -c "cd /app/ && snapcraft"
    - sudo chown -R $USER:$USER neuronify*.snap
    - ls -l .
    deploy:
      skip_cleanup: true
      provider: releases
      file: .snapcraft/neuronify*.snap
      file_glob: true
      on:
        tags: true
      api_key:
        secure: WJ9YTjPf8GWZ4PmdVoPubtL0CBU+cAIIMFjTpeOKwOLX1vH3zFkdwAz1nbY28CWWhm+YQwWVWwByZOI9hePsf5t6wtkWfJB4wzgrKEcIyKHMHmjaMYc+fp6V//3f7Z4Kc6vYn7wNNy1i9zgA8VVr2A4u8Rf1i7Euio4SLpey17w=
install:
- qmake
- make
script:
- echo "Finished"
