language: cpp
branches:
  except:
    - appveyor
matrix:
    include:
        - os: osx
          before_install:
              - brew update
              - brew install qt5
              - brew link --force qt5
        - os: linux
          dist: trusty
          sudo: required
          before_install:
              - sudo apt-add-repository -y ppa:beineri/opt-qt57-precise
              - sudo apt-get -qq update
              - sudo apt-get -qq install qt573d qt57charts-no-lgpl qt57datavis-no-lgpl qt57declarative qt57svg
              - export PATH=$PATH:/opt/qt57/bin
install:
    - qmake
    - make
script:
    - echo "Finished"
