language: cpp
branches:
  except:
  - appveyor
matrix:
  include:
  - os: osx
    before_install:
      - brew update
      - brew install p7zip
      - bash .travis/qt5-mac.sh $(pwd) extra-charts 3d base declarative graphicaleffects imageformats macextras multimedia quickcontrols quickcontrols2 sensors svg tools translations xmlpatterns
      - export PATH=$(pwd)/5.7/clang_64/bin:$PATH
    before_deploy:
      - git clone https://github.com/iltommi/macdeployqtfix.git
      - python macdeployqtfix/macdeployqtfix.py neuronify.app/Contents/MacOS/neuronify /usr/local
      - macdeployqt neuronify.app -qmldir=. -dmg
    deploy:
      skip_cleanup: true
      provider: releases
      file: neuronify.dmg
      on:
        tags: true
      api_key:
        secure: WJ9YTjPf8GWZ4PmdVoPubtL0CBU+cAIIMFjTpeOKwOLX1vH3zFkdwAz1nbY28CWWhm+YQwWVWwByZOI9hePsf5t6wtkWfJB4wzgrKEcIyKHMHmjaMYc+fp6V//3f7Z4Kc6vYn7wNNy1i9zgA8VVr2A4u8Rf1i7Euio4SLpey17w=
  - os: linux
    dist: trusty
    sudo: required
    services: docker
    #before_install:
    #- sudo apt-add-repository -y ppa:beineri/opt-qt57-trusty
    #- sudo apt-get -qq update
    #- sudo apt-get -qq install qt573d qt57charts-no-lgpl qt57datavis-no-lgpl qt57declarative
      #qt57svg
    #- export PATH=/opt/qt57/bin:$PATH
    before_deploy:
    - mkdir output
    #- cp neuronify .snapcraft/
    #- cp -r /opt/qt57/lib .snapcraft/
    #- cp -r /opt/qt57/qml .snapcraft/
    #- cp -r /opt/qt57/plugins .snapcraft/
    - touch .snapcraft/neuronify
    - mkdir .snapcraft/lib
    - mkdir .snapcraft/qml
    - mkdir .snapcraft/plugins
    - docker build -t ovilab/neuronify -f .docker/Dockerfile .
    - docker run -v $(pwd)/output:/app/output ovilab/neuronify  bash -c "cd .snapcraft && snapcraft snap && mv neuronify*.snap ../output/"
    - sudo chown -R $USER:$USER output
    - ls -l output
    deploy:
      skip_cleanup: true
      provider: releases
      file: neuronify.snap
      #on:
        #tags: true
      on:
        branch: travistest
      api_key:
        secure: WJ9YTjPf8GWZ4PmdVoPubtL0CBU+cAIIMFjTpeOKwOLX1vH3zFkdwAz1nbY28CWWhm+YQwWVWwByZOI9hePsf5t6wtkWfJB4wzgrKEcIyKHMHmjaMYc+fp6V//3f7Z4Kc6vYn7wNNy1i9zgA8VVr2A4u8Rf1i7Euio4SLpey17w=
install:
- echo "Testing"
#- qmake
#- make
script:
- echo "Finished"
