install:
  - set QTDIR=C:\Qt\5.7\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
build_script:
  - git submodule update --init --recursive
  - qmake neuronify.pro
  - nmake
