install:
  - set QTDIR=C:\Qt\5.7\msvc2013_64
  - set PATH=%PATH%;%QTDIR%\bin
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
build_script:
  - git submodule update --init --recursive
  - qmake neuronify.pro
  - nmake
